#!/usr/bin/python3

import pathlib
import yaml

from common import (
    run_read, analyse_module, analyse_repo, upsert_repo, sqlite_db,
    make_common_schema, scalar, get_environ, analyse,
)

BASE_DIRECTORY = pathlib.Path(__file__).resolve().parent
CLONE_DIRECTORY = BASE_DIRECTORY / "analyse"
OUTPUT_DIRECTORY = BASE_DIRECTORY / "output"
CONFIG_FILE = BASE_DIRECTORY / "config.yml"


def make_schema(db):
    """Create the database schema."""
    print("Creating database schema (if not exists)")
    db.execute("PRAGMA foreign_keys = ON")
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS "commit" (
            id INTEGER PRIMARY KEY,
            repo_id INTEGER,
            hash TEXT,
            date TEXT,
            author TEXT,
            mail TEXT,
            message TEXT,
            FOREIGN KEY(repo_id) REFERENCES repo(id),
            UNIQUE(repo_id, hash)
        )
        """
    )
    make_common_schema(db, with_module=True)
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS module_commit (
            commit_id INTEGER,
            module_id INTEGER,
            FOREIGN KEY(commit_id) REFERENCES "commit"(id),
            FOREIGN KEY(module_id) REFERENCES module(id),
            PRIMARY KEY(commit_id, module_id)
        )
        """
    )


def upsert_module(db, repo_id, module_name, module_data):
    """Get the module id from the database, or insert it if it doesn't exist."""
    return scalar(
        db,
        """
        INSERT INTO module (repo_id, name, title, author, depends, maintainers, development_status, summary, last_version)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(repo_id, name)
        DO UPDATE SET
            title = EXCLUDED.title,
            author = EXCLUDED.author,
            depends = EXCLUDED.depends,
            maintainers = EXCLUDED.maintainers,
            development_status = EXCLUDED.development_status,
            summary = EXCLUDED.summary,
            last_version = EXCLUDED.last_version
        RETURNING id
        """,
        repo_id,
        module_name,
        module_data["name"],
        ",".join(module_data["author"])
        if type(module_data["author"]) == list
        else module_data["author"],
        ",".join(module_data["depends"]),
        ",".join(module_data["maintainers"]),
        module_data["development_status"],
        module_data["summary"],
        module_data["last_version"],
    )


def upsert_commit(
    db, repo_id, commit_hash, commit_date, commit_author, commit_mail,
    commit_message
):
    """Get the commit id from the database, or insert it if it doesn't exist."""
    return scalar(
        db,
        """
        INSERT INTO "commit" (repo_id, hash, date, author, mail, message)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(repo_id, hash)
        DO UPDATE SET
            date = EXCLUDED.date,
            author = EXCLUDED.author,
            mail = EXCLUDED.mail,
            message = EXCLUDED.message
        RETURNING id
        """,
        repo_id,
        commit_hash,
        commit_date,
        commit_author,
        commit_mail,
        commit_message,
    )


def insert_module_commit(db, commit_id, module_id):
    """Insert a module commit in the database."""
    db.execute(
        """
        INSERT INTO module_commit (commit_id, module_id)
        VALUES (?, ?)
        """,
        (
            commit_id,
            module_id,
        ),
    )


def fetch_last_commit(db, repo_id):
    """Fetch the last commit of a repo."""
    # Use order by id and not date since commits can be out of order
    return scalar(
        db,
        """
        SELECT hash
        FROM "commit"
        WHERE repo_id = ?
        ORDER BY id DESC
        LIMIT 1
        """,
        repo_id,
    )


def analyse_commits(db, org, repo_id, path, modules):
    """Analyse the commits of a repo and store it in the database."""
    # Update modules
    module_ids = {
        module_name: upsert_module(db, repo_id, module_name, module_data)
        for module_name, module_data in modules.items()
    }
    if org == "odoo":
        return

    last_commit = fetch_last_commit(db, repo_id)
    target = f"{last_commit}..HEAD" if last_commit else "HEAD"
    print(f"Analyzing commits for {path.name} ({target})")
    rev_list = run_read(path, "git", "rev-list", target).strip()
    if not rev_list:
        return

    commits = rev_list.split("\n")
    for commit in reversed(commits):
        commit_data = run_read(
            path,
            "git",
            "show",
            "--pretty=format:%aI%x18%an%x18%s%x18%ae",
            "--name-only",
            commit,
        ).strip()
        header, *files = commit_data.split("\n")
        commit_date, commit_author, commit_message, commit_mail = header.split(
            "\x18", 3
        )
        commit_id = upsert_commit(
            db, repo_id, commit, commit_date, commit_author, commit_mail,
            commit_message,
        )
        modules = {
            module
            for file in files
            for module in [file.split("/")[0]]
            if module in module_ids
        }
        for module in modules:
            insert_module_commit(db, commit_id, module_ids[module])


def process_repo(db, org, repo, version, path, result):
    result[org][repo] = analyse_repo(path, analyse_module)
    analyse_commits(
        db, org, upsert_repo(db, org, repo), path, result[org][repo]
    )


def main():
    """Run the main analysis, writing the results to yaml files and sqlite db."""
    config, version, restrict, clean_db = get_environ(CONFIG_FILE)

    OUTPUT_DIRECTORY.mkdir(exist_ok=True)
    CLONE_DIRECTORY.mkdir(exist_ok=True)

    download_url = (
        "https://github.com/akretion/odoo-module-tracker/raw/gh-pages"
    )
    with sqlite_db(
        OUTPUT_DIRECTORY / f"{version}.db", make_schema, clean=clean_db,
        download_url=download_url
    ) as db:
        result = analyse(
            db, CLONE_DIRECTORY, config, version, restrict, process_repo
        )
        result["odoo"] = {}
        odoo_path = pathlib.Path(
            f'~/code/odoo/odoo/{version}/addons'
        ).expanduser()
        process_repo(db, "odoo", "odoo", version, odoo_path, result)
        enterprise_path = pathlib.Path(
            f'~/code/odoo/enterprise/{version}'
        ).expanduser()
        process_repo(db, "odoo", "enterprise", version, enterprise_path, result)

    data = yaml.safe_dump(result)
    with open(OUTPUT_DIRECTORY / f"{version}.yml", "w") as output:
        output.write(data)

    for org, repos in result.items():
        for repo in repos:
            result[org][repo] = list(result[org][repo].keys())

    data = yaml.safe_dump(result)
    with open(OUTPUT_DIRECTORY / f"module-list-{version}.yml", "w") as output:
        output.write(data)


if __name__ == "__main__":
    main()
