#!/usr/bin/python3

import cloc
import pathlib

from common import (
    analyse_repo, upsert_repo, sqlite_db, make_common_schema, scalar,
    get_environ, analyse,
)

BASE_DIRECTORY = pathlib.Path(__file__).resolve().parent
CLONE_DIRECTORY = BASE_DIRECTORY / "analyse"
OUTPUT_DIRECTORY = BASE_DIRECTORY / "output"
CONFIG_FILE = BASE_DIRECTORY / "config.yml"


def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text


def analyse_module(path):
    """Analyse a module and return a dict of its data."""
    if not path.is_dir():
        return
    if not any([(path / f).exists() for f in cloc.MANIFEST_NAMES]):
        return
    c = cloc.Cloc()
    c.count_path(str(path))
    module = c.modules[path.name]
    result = {
        "files": [
            (remove_prefix(f, f"{path}/"), module[f])
            for f in sorted(module.keys())
        ],
        "total": sum(c.total.values()),
        "code": sum(c.code.values()),
    }
    return result


def make_schema(db):
    """Create the database schema."""
    print("Creating database schema (if not exists)")
    db.execute("PRAGMA foreign_keys = ON")
    make_common_schema(db, with_module=False)
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_module (
            id INTEGER PRIMARY KEY,
            repo_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(repo_id) REFERENCES repo(id)
            UNIQUE(repo_id, name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_file (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id)
            UNIQUE(module_id, name)
        )
        """
    )


def upsert_module(db, repo_id, module_name, module_data):
    """Get the module id from the database, or insert it if it doesn't exist."""
    module_id = scalar(
        db,
        """
        INSERT INTO cloc_module (repo_id, name, total, code)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(repo_id, name)
        DO UPDATE SET
            total = EXCLUDED.total,
            code = EXCLUDED.code
        RETURNING id
        """,
        repo_id,
        module_name,
        module_data["total"],
        module_data["code"],
    )
    for name, (code, total) in module_data["files"]:
        scalar(
            db,
            """
            INSERT INTO cloc_file (module_id, name, total, code)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(module_id, name)
            DO UPDATE SET
                total = EXCLUDED.total,
                code = EXCLUDED.code
            RETURNING id
            """,
            module_id,
            name,
            total,
            code,
        )
    return module_id


def process_repo(db, org, repo, version, path, result):
    result[org][repo] = analyse_repo(path, analyse_module)
    repo_id = upsert_repo(db, org, repo)
    for module_name, module_data in result[org][repo].items():
        upsert_module(db, repo_id, module_name, module_data)


def main():
    """Run the main analysis, writing the results to sqlite db."""
    config, version, restrict, clean_db = get_environ(CONFIG_FILE)

    OUTPUT_DIRECTORY.mkdir(exist_ok=True)
    CLONE_DIRECTORY.mkdir(exist_ok=True)

    with sqlite_db(
        OUTPUT_DIRECTORY / f"modules_{version}_analysis.db", make_schema,
        clean=clean_db
    ) as db:
        result = analyse(
            db, CLONE_DIRECTORY, config, version, restrict, process_repo
        )


if __name__ == "__main__":
    main()
