#!/usr/bin/python3

import astroid
import cloc
import os
import pathlib

from common import (
    analyse_repo, upsert_repo, sqlite_db, make_common_schema, scalar,
    get_environ, analyse,
)

BASE_DIRECTORY = pathlib.Path(__file__).resolve().parent
CLONE_DIRECTORY = BASE_DIRECTORY / "analyse"
OUTPUT_DIRECTORY = BASE_DIRECTORY / "output"
CONFIG_FILE = BASE_DIRECTORY / "config.yml"


def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text


def analyse_module(path):
    """Analyse a module and return a dict of its data."""
    if not path.is_dir():
        return
    if not any([(path / f).exists() for f in cloc.MANIFEST_NAMES]):
        return
    c = cloc.Cloc()
    c.count_path(str(path))
    module = c.modules[path.name]
    result = {
        "files": [
            (remove_prefix(f, f"{path}/"), module[f])
            for f in sorted(module.keys())
        ],
        "total": sum(c.total.values()),
        "code": sum(c.code.values()),
    }
    result['models'] = {}
    analyse_path(path, result)
    return result


def analyse_path(path, result):
    for file in path.iterdir():
        if file.name in cloc.MANIFEST_NAMES or (
            file.name in ['__init__.py', 'tests']
        ):
            continue
        if file.is_dir():
            analyse_path(file, result)
        ext = os.path.splitext(file.name)[1].lower()
        if ext != '.py':
            continue
        try:
            models = analyse_model(file)
        except Exception as e:
            print(f"Error analysing {file}", e)
            continue
        for model, data in models.items():
            if not model in result['models']:
                result['models'][model] = data
                continue
            existing_data = result['models'][model]
            if model != data['inherit']:
                existing_data['inherit'] = data['inherit']
            existing_data['methods'].extend(data['methods'])


def analyse_model(path):
    result = {}
    with open(path, 'r') as f:
        has_bom = ord(f.read(1) or 'a') == 65279
    with open(path, 'r') as f:
        if has_bom:
            f.read(1)
        try:
            tree = astroid.parse(f.read())
        except astroid.exceptions.AstroidSyntaxError as e:
            print(f"Syntax error in {path}", e)
            return result
    names = {}
    for body in tree.body:
        if isinstance(body, astroid.ImportFrom):
            for from_name, to_name in body.names:
                if to_name:
                    names[to_name] = from_name
            continue
        if not isinstance(body, astroid.ClassDef):
            continue
        name = None
        inherit = None
        methods = []
        is_controller = False
        for node in body.body:
            if isinstance(node, astroid.FunctionDef):
                methods.append(node.name)
                continue
            if not isinstance(node, astroid.Assign):
                continue
            try:
                node_name = node.targets[0].name
            except AttributeError:
                try:
                    node_name = node.targets[0].attrname
                except AttributeError:
                    continue
            if node_name == '_inherit':
                if isinstance(node.value, astroid.Const):
                    inherit = node.value.value
                elif (
                    isinstance(node.value, astroid.Name)
                    and node.value.name == '_name'
                ):
                    inherit = name
                else:
                    inherit = [
                        elt.value if isinstance(elt, astroid.Const)
                        else name if isinstance(elt, astroid.Name)
                        else elt
                        for elt in node.value.elts
                    ]
                    if len(inherit) == 1:
                        inherit = inherit[0]
            elif node_name == '_name':
                name = node.value.inferred()[0].value
        if not name and inherit:
            name = inherit
        routes = analyse_routes(path, body)
        if routes and not name:
            is_controller = True
            name = body.name
            inherit = [
                names.get(b.name, b.name)
                if type(b) == astroid.Name
                else b.attrname for b in body.bases
            ]
        if name:
            result[name] = {
                'inherit': inherit,
                'methods': methods,
                'routes': routes,
                'path': str(path),
                'is_controller': is_controller,
            }
    return result


def analyse_routes(path, cls):
    routes = {}
    for element in cls.body:
        if not isinstance(element, astroid.FunctionDef):
            continue
        if not element.decorators:
            continue
        route_nodes = []
        for n in element.decorators.nodes:
            if not type(n) == astroid.Call:
                continue
            if type(n.func) == astroid.Attribute:
                is_route = n.func.attrname == 'route'
            else:
                is_route = n.func.name == 'route'
            if is_route:
                route_nodes.append(n)
        if not route_nodes:
            continue
        routes[element.name] = []
        for node in route_nodes:
            try:
                if type(node.args[0]) == astroid.Const:
                    routes[element.name].append(node.args[0].value)
                    continue
            except IndexError:
                continue
            if type(node.args[0]) in [astroid.Name, astroid.JoinedStr]:
                routes[element.name].append(
                    node.args[0].inferred()[0].value
                )
                continue
            for elt in node.args[0].inferred()[0].elts:
                routes[element.name].append(elt.inferred()[0].value)
    return routes


def make_schema(db):
    """Create the database schema."""
    print("Creating database schema (if not exists)")
    db.execute("PRAGMA foreign_keys = ON")
    make_common_schema(db, with_module=False)
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_module (
            id INTEGER PRIMARY KEY,
            repo_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(repo_id) REFERENCES repo(id)
            UNIQUE(repo_id, name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_file (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id)
            UNIQUE(module_id, name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS model (
            id INTEGER PRIMARY KEY,
            name TEXT,
            is_new BOOLEAN,
            is_controller BOOLEAN,
            UNIQUE(name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS module_model (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            model_id INTEGER,
            path TEXT,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id),
            FOREIGN KEY(model_id) REFERENCES model(id),
            UNIQUE(module_id, model_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS inherit (
            id INTEGER PRIMARY KEY,
            module_model_id INTEGER,
            inherit_id INTEGER,
            FOREIGN KEY(module_model_id) REFERENCES module_model(id),
            FOREIGN KEY(inherit_id) REFERENCES model(id),
            UNIQUE(module_model_id, inherit_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS method (
            id INTEGER PRIMARY KEY,
            name TEXT,
            UNIQUE(name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS module_method (
            id INTEGER PRIMARY KEY,
            module_model_id INTEGER,
            method_id INTEGER,
            is_new BOOLEAN,
            FOREIGN KEY(module_model_id) REFERENCES module_model(id),
            FOREIGN KEY(method_id) REFERENCES method(id),
            UNIQUE(module_model_id, method_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS path (
            id INTEGER PRIMARY KEY,
            path TEXT,
            UNIQUE(path)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS route (
            id INTEGER PRIMARY KEY,
            module_method_id INTEGER,
            path_id INTEGER,
            FOREIGN KEY(module_method_id) REFERENCES module_method(id),
            FOREIGN KEY(path_id) REFERENCES path(id),
            UNIQUE(module_method_id, path_id)
        )
        """
    )


def upsert_module(db, repo_id, module_name, module_data):
    """Get the module id from the database, or insert it if it doesn't exist."""
    module_id = scalar(
        db,
        """
        INSERT INTO cloc_module (repo_id, name, total, code)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(repo_id, name)
        DO UPDATE SET
            total = EXCLUDED.total,
            code = EXCLUDED.code
        RETURNING id
        """,
        repo_id,
        module_name,
        module_data["total"],
        module_data["code"],
    )
    for name, (code, total) in module_data["files"]:
        scalar(
            db,
            """
            INSERT INTO cloc_file (module_id, name, total, code)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(module_id, name)
            DO UPDATE SET
                total = EXCLUDED.total,
                code = EXCLUDED.code
            RETURNING id
            """,
            module_id,
            name,
            total,
            code,
        )
    for model_name, model_data in module_data['models'].items():
        if not model_name:
            continue
        model_id = upsert_model(db, model_name, model_data)
        model_inherits = model_data['inherit']
        model_methods = model_data['methods']
        model_routes = model_data['routes']
        if isinstance(model_inherits, list):
            ids = [upsert_simple(
                db, 'model', 'name', inherit
            ) for inherit in model_inherits]
        elif model_inherits:
            ids = [upsert_simple(db, 'model', 'name', model_inherits)]
        else:
            ids = [None]
        module_model_id = upsert_module_model(
            db, module_id, model_id, model_data['path'],
        )
        for inherit_id in ids:
            if not inherit_id:
                continue
            scalar(
                db,
                """
                INSERT INTO inherit (module_model_id, inherit_id)
                VALUES (?, ?)
                ON CONFLICT(module_model_id, inherit_id)
                DO UPDATE SET
                    module_model_id = EXCLUDED.module_model_id,
                    inherit_id = EXCLUDED.inherit_id
                RETURNING id
                """,
                module_model_id,
                inherit_id,
            )
        for method in model_methods:
            method_id = upsert_simple(db, 'method', 'name', method)
            module_method_id = scalar(
                db,
                """
                INSERT INTO module_method (module_model_id, method_id)
                VALUES (?, ?)
                ON CONFLICT(module_model_id, method_id)
                DO UPDATE SET
                    module_model_id = EXCLUDED.module_model_id,
                    method_id = EXCLUDED.method_id
                RETURNING id
                """,
                module_model_id,
                method_id,
            )
            if not method in model_routes:
                continue
            paths = model_routes[method]
            for path in model_routes[method] or [None]:
                if path:
                    path_id = upsert_simple(db, 'path', 'path', path)
                else:
                    path_id = None
                scalar(
                    db,
                    """
                    INSERT INTO route (module_method_id, path_id)
                    VALUES (?, ?)
                    ON CONFLICT(module_method_id, path_id)
                    DO UPDATE SET
                        module_method_id = EXCLUDED.module_method_id,
                        path_id = EXCLUDED.path_id
                    RETURNING id
                    """,
                    module_method_id,
                    path_id,
                )
    return module_id


def upsert_model(db, model_name, model_data):
    record_id = scalar(
        db,
        f"""
        INSERT INTO model (name, is_controller)
        VALUES (?, ?)
        ON CONFLICT(name)
        DO UPDATE SET
            is_controller = EXCLUDED.is_controller
        RETURNING id
        """,
        model_name,
        model_data['is_controller'],
    )
    return record_id


def upsert_simple(db, table, column, value):
    record_id = scalar(
        db,
        f"""
        INSERT INTO {table} ({column})
        VALUES (?)
        ON CONFLICT({column})
        DO UPDATE SET
            {column} = EXCLUDED.{column}
        RETURNING id
        """,
        value,
    )
    return record_id


def upsert_module_model(db, module_id, model_id, path):
    model_id = scalar(
        db,
        """
        INSERT INTO module_model (module_id, model_id, path)
        VALUES (?, ?, ?)
        ON CONFLICT(module_id, model_id)
        DO UPDATE SET
            path = EXCLUDED.path
        RETURNING id
        """,
        module_id,
        model_id,
        path,
    )
    return model_id


def process_repo(db, org, repo, version, path, result):
    result[org][repo] = analyse_repo(path, analyse_module)
    repo_id = upsert_repo(db, org, repo)
    for module_name, module_data in result[org][repo].items():
        upsert_module(db, repo_id, module_name, module_data)


def main():
    """Run the main analysis, writing the results to sqlite db."""
    config, version, restrict, clean_db = get_environ(CONFIG_FILE)

    OUTPUT_DIRECTORY.mkdir(exist_ok=True)
    CLONE_DIRECTORY.mkdir(exist_ok=True)

    with sqlite_db(
        OUTPUT_DIRECTORY / f"modules_{version}_analysis.db", make_schema,
        clean=clean_db
    ) as db:
        result = analyse(
            db, CLONE_DIRECTORY, config, version, restrict, process_repo
        )
        result["odoo"] = {}
        print('Processing odoo/odoo')
        odoo_path = pathlib.Path(
            f'~/code/odoo/odoo/{version}/odoo/addons'
        ).expanduser()
        process_repo(db, "odoo", "odoo", version, odoo_path, result)
        print('Processing odoo/enterprise')
        odoo_path = pathlib.Path(
            f'~/code/odoo/odoo/{version}/addons'
        ).expanduser()
        process_repo(db, "odoo", "odoo", version, odoo_path, result)
        enterprise_path = pathlib.Path(
            f'~/code/odoo/enterprise/{version}'
        ).expanduser()
        process_repo(db, "odoo", "enterprise", version, enterprise_path, result)


if __name__ == "__main__":
    main()
