#!/usr/bin/python3

import astroid
import cloc
import os
import pathlib

from common import (
    analyse_repo, upsert_repo, sqlite_db, make_common_schema, scalar,
    get_environ, analyse,
)

BASE_DIRECTORY = pathlib.Path(__file__).resolve().parent
CLONE_DIRECTORY = BASE_DIRECTORY / "analyse"
OUTPUT_DIRECTORY = BASE_DIRECTORY / "output"
CONFIG_FILE = BASE_DIRECTORY / "config.yml"


def remove_prefix(text, prefix):
    if text.startswith(prefix):
        return text[len(prefix):]
    return text


def analyse_module(path):
    """Analyse a module and return a dict of its data."""
    if not path.is_dir():
        return
    if not any([(path / f).exists() for f in cloc.MANIFEST_NAMES]):
        return
    c = cloc.Cloc()
    c.count_path(str(path))
    module = c.modules[path.name]
    result = {
        "files": [
            (remove_prefix(f, f"{path}/"), module[f])
            for f in sorted(module.keys())
        ],
        "total": sum(c.total.values()),
        "code": sum(c.code.values()),
    }
    result['models'] = {}
    for file in path.iterdir():
        if file.name in cloc.MANIFEST_NAMES or (
            file.name in ['__init__.py', 'tests']
        ):
            continue
        if file.is_dir():
            for subfile in file.iterdir():
                ext = os.path.splitext(subfile.name)[1].lower()
                if ext == '.py':
                    result['models'].update(analyse_model(subfile))
    return result


def analyse_model(path):
    result = {}
    with open(path, 'r') as f:
        has_bom = ord(f.read(1) or 'a') == 65279
    with open(path, 'r') as f:
        if has_bom:
            f.read(1)
        try:
            tree = astroid.parse(f.read())
        except astroid.exceptions.AstroidSyntaxError as e:
            print(f"Syntax error in {path}", e)
            return result
        for body in tree.body:
            if not isinstance(body, astroid.ClassDef):
                continue
            name = None
            inherit = None
            methods = []
            for node in body.body:
                if isinstance(node, astroid.FunctionDef):
                    methods.append(node.name)
                    continue
                if not isinstance(node, astroid.Assign):
                    continue
                try:
                    node_name = node.targets[0].name
                except AttributeError:
                    node_name = node.targets[0].attrname
                if node_name == '_inherit':
                    if isinstance(node.value, astroid.Const):
                        inherit = node.value.value
                    elif (
                        isinstance(node.value, astroid.Name)
                        and node.value.name == '_name'
                    ):
                        inherit = name
                    else:
                        inherit = [
                            est.value if isinstance(est, astroid.Const)
                            else name if isinstance(est, astroid.Name)
                            else est
                            for est in node.value.elts
                        ]
                        if len(inherit) == 1:
                            inherit = inherit[0]
                elif node_name == '_name':
                    name = node.value.value
            if not name:
                name = inherit
            result[name] = {
                'inherit': inherit,
                'methods': methods,
            }
    return result


def make_schema(db):
    """Create the database schema."""
    print("Creating database schema (if not exists)")
    db.execute("PRAGMA foreign_keys = ON")
    make_common_schema(db, with_module=False)
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_module (
            id INTEGER PRIMARY KEY,
            repo_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(repo_id) REFERENCES repo(id)
            UNIQUE(repo_id, name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS cloc_file (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            name TEXT,
            total INTEGER,
            code INTEGER,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id)
            UNIQUE(module_id, name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS model (
            id INTEGER PRIMARY KEY,
            name TEXT,
            UNIQUE(name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS module_model (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            model_id INTEGER,
            inherit_id INTEGER,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id),
            FOREIGN KEY(model_id) REFERENCES model(id),
            FOREIGN KEY(inherit_id) REFERENCES model(id),
            UNIQUE(module_id, model_id, inherit_id)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS method (
            id INTEGER PRIMARY KEY,
            name TEXT,
            UNIQUE(name)
        )
        """
    )
    db.execute(
        """
        CREATE TABLE IF NOT EXISTS module_method (
            id INTEGER PRIMARY KEY,
            module_id INTEGER,
            model_id INTEGER,
            method_id INTEGER,
            FOREIGN KEY(module_id) REFERENCES cloc_module(id),
            FOREIGN KEY(model_id) REFERENCES model(id),
            FOREIGN KEY(method_id) REFERENCES method(id),
            UNIQUE(module_id, model_id, method_id)
        )
        """
    )


def upsert_module(db, repo_id, module_name, module_data):
    """Get the module id from the database, or insert it if it doesn't exist."""
    module_id = scalar(
        db,
        """
        INSERT INTO cloc_module (repo_id, name, total, code)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(repo_id, name)
        DO UPDATE SET
            total = EXCLUDED.total,
            code = EXCLUDED.code
        RETURNING id
        """,
        repo_id,
        module_name,
        module_data["total"],
        module_data["code"],
    )
    for name, (code, total) in module_data["files"]:
        scalar(
            db,
            """
            INSERT INTO cloc_file (module_id, name, total, code)
            VALUES (?, ?, ?, ?)
            ON CONFLICT(module_id, name)
            DO UPDATE SET
                total = EXCLUDED.total,
                code = EXCLUDED.code
            RETURNING id
            """,
            module_id,
            name,
            total,
            code,
        )
    for model_name, model_data in module_data['models'].items():
        if not model_name:
            continue
        model_id = upsert_model(db, model_name)
        model_inherits = model_data['inherit']
        model_methods = model_data['methods']
        if isinstance(model_inherits, list):
            ids = [upsert_model(db, inherit) for inherit in model_inherits]
        elif model_inherits:
            ids = [upsert_model(db, model_inherits)]
        else:
            ids = [None]
        for inherit_id in ids:
            scalar(
                db,
                """
                INSERT INTO module_model (module_id, model_id, inherit_id)
                VALUES (?, ?, ?)
                ON CONFLICT(module_id, model_id, inherit_id)
                DO UPDATE SET
                    module_id = EXCLUDED.module_id,
                    model_id = EXCLUDED.model_id,
                    inherit_id = EXCLUDED.inherit_id
                RETURNING id
                """,
                module_id,
                model_id,
                inherit_id,
            )
        for method in model_methods:
            method_id = upsert_method(db, method)
            scalar(
                db,
                """
                INSERT INTO module_method (module_id, model_id, method_id)
                VALUES (?, ?, ?)
                ON CONFLICT(module_id, model_id, method_id)
                DO UPDATE SET
                    module_id = EXCLUDED.module_id,
                    model_id = EXCLUDED.model_id,
                    method_id = EXCLUDED.method_id
                RETURNING id
                """,
                module_id,
                model_id,
                method_id,
            )
        continue
    return module_id


def upsert_model(db, model_name):
    model_id = scalar(
        db,
        """
        INSERT INTO model (name)
        VALUES (?)
        ON CONFLICT(name)
        DO UPDATE SET
            name = EXCLUDED.name
        RETURNING id
        """,
        model_name,
    )
    return model_id


def upsert_method(db, method_name):
    method_id = scalar(
        db,
        """
        INSERT INTO method (name)
        VALUES (?)
        ON CONFLICT(name)
        DO UPDATE SET
            name = EXCLUDED.name
        RETURNING id
        """,
        method_name,
    )
    return method_id


def process_repo(db, org, repo, version, path, result):
    result[org][repo] = analyse_repo(path, analyse_module)
    repo_id = upsert_repo(db, org, repo)
    for module_name, module_data in result[org][repo].items():
        upsert_module(db, repo_id, module_name, module_data)


def main():
    """Run the main analysis, writing the results to sqlite db."""
    config, version, restrict, clean_db = get_environ(CONFIG_FILE)

    OUTPUT_DIRECTORY.mkdir(exist_ok=True)
    CLONE_DIRECTORY.mkdir(exist_ok=True)

    with sqlite_db(
        OUTPUT_DIRECTORY / f"modules_{version}_analysis.db", make_schema,
        clean=clean_db
    ) as db:
        result = analyse(
            db, CLONE_DIRECTORY, config, version, restrict, process_repo
        )
        result["odoo"] = {}
        odoo_path = pathlib.Path(
            f'~/code/odoo/odoo/{version}/addons'
        ).expanduser()
        process_repo(db, "odoo", "odoo", version, odoo_path, result)
        enterprise_path = pathlib.Path(
            f'~/code/odoo/enterprise/{version}'
        ).expanduser()
        process_repo(db, "odoo", "enterprise", version, enterprise_path, result)


if __name__ == "__main__":
    main()
